#
# Order of deployment required to prevent chicken versus the egg issues:
#  0. For all deployment phases:
#       export AI_PROXY="${jumphost_name}"
#       export AI_INVENTORY="${cluster_name}_hosts.ini"
#       ANSIBLE_VAULT_PASSWORD_FILE=".vault_pass.txt.${cluster_name}"
#
#  1. Use standard CentOS cloud image user 'centos' or 'root' user and without host key checking:
#       export ANSIBLE_HOST_KEY_CHECKING=False
#       ansible-playbook -i inventory.py -u centos -l 'jumphost,cluster'  single_role_playbooks/admin-users.yml
#       ansible-playbook -i inventory.py -u root   -l 'docs'              single_role_playbooks/admin-users.yml
#  2. Use local admin user's account and without host key checking:
#       export ANSIBLE_HOST_KEY_CHECKING=False
#       ansible-playbook -i inventory.py -u [admin_account] single_role_playbooks/ssh_host_signer.yml
#  3. Use local admin user's account and with strict host key checking to deploy everything else:
#       export ANSIBLE_HOST_KEY_CHECKING=True
#       ansible-playbook -i inventory.py -u [admin_account] cluster.yml
#     This will configure:
#       A. Jumphost first as it is required to access the other machines.
#       B. SAI as it is required to 
#           * configure layout on shared storage devices used by other machines.
#           * configure Slurm control and Slurm database.
#       C. DAI
#       D. UI
#       E. Compute nodes
#       F. Documentation server
#
- name: 'Sanity checks before we start.'
  hosts: all
  pre_tasks:
    - name: 'Verify Ansible version meets requirements.'
      assert:
        that: "ansible_version.full is version_compare('2.4', '>=')"
        msg: 'You must update Ansible to at least 2.4.x to use this playbook.'

- name: 'A. Roles for jumphosts.'
  hosts: jumphost
  roles:
    - admin-users
    - ssh_host_signer
    - ssh_known_hosts
    - yum-repos
    - logins
    - {role: geerlingguy.repo-epel, become: true}
    - ldap
    - static-hostname-lookup
    - sshd
    - node_exporter
    - {role: geerlingguy.security, become: true}
    - prom_proxy
    - regular-users
  tasks:
    - name: 'Install cron job to reboot jumphost regularly to activate kernel updates.'
      cron:
        name: 'Reboot to load new kernel.'
        weekday: '1'
        minute: '45'
        hour: '11'
        user: root
        job: /bin/needs-restarting -r >/dev/null 2>&1 || /sbin/shutdown -r +60 "Restarting to apply updates..."
        cron_file: reboot
      become: true

- name: 'B. Roles for SAIs.'
  hosts:
    - sys-admin-interface
  roles:
    - admin-users
    - ssh_host_signer
    - ssh_known_hosts
    - spacewalk_client
    - logins
    - figlet_hostname
    - mount-volume
    - ldap
    - node_exporter
    - static-hostname-lookup
    - cluster
    - sshd
    - resolver
    - shared_storage
    - regular-users

- hosts: slurm-management
  roles:
    - slurm-management
    - prom_server
    - grafana
    - {role: cadvisor, become: true}
  vars:
    # These variables are needed by the mariadb role.
    # Which is a depencency of the slurm-management role.
    # See roles/slurm/meta/main.yml
    hostname_node0: "{{ ansible_hostname }}"
    ip_node0: "{{ ansible_default_ipv4['address'] }}"

- name: 'C. Roles for DAIs.'
  hosts: deploy-admin-interface
  roles:
    - admin-users
    - ssh_host_signer
    - ssh_known_hosts
    - spacewalk_client
    - logins
    - figlet_hostname
    - mount-volume
    - build-environment
    - ldap
    - node_exporter
    - static-hostname-lookup
    - cluster
    - sshd
    - resolver
    - shared_storage
    - regular-users
    - envsync

- name: 'D. Roles for UIs.'
  hosts: user-interface
  roles:
    - admin-users
    - ssh_host_signer
    - ssh_known_hosts
    - spacewalk_client
    - logins
    - figlet_hostname
    - build-environment
    - ldap
    - node_exporter
    - static-hostname-lookup
    - cluster
    - sshd
    - resolver
    - shared_storage
    - slurm_exporter
    - slurm-client
    - regular-users
    - sudoers

- name: 'E. Roles for compute nodes.'
  hosts: compute-vm
  roles:
    - admin-users
    - ssh_host_signer
    - ssh_known_hosts
    - spacewalk_client
    - logins
    - figlet_hostname
    - mount-volume
    - ldap
    - node_exporter
    - static-hostname-lookup
    - cluster
    - sshd
    - resolver
    - shared_storage
    - slurm-client
    - regular-users
  tasks:
    - name: 'increase the file limit'
      lineinfile:
        path: '/etc/security/limits.conf'
        line: '*       hard    nofile          65536'
      become: true

- name: 'F. Roles for documentation servers.'
  hosts:
    - docs
  roles:
    - admin-users
    - ssh_host_signer
    - online_docs
...
